# Generated by Django 3.2.9 on 2021-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someposts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
