# Generated by Django 3.2.9 on 2021-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='someposts',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
