# Generated by Django 3.2.9 on 2021-11-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211124_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='someposts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
    ]
