# Generated by Django 3.2.9 on 2021-11-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_someposts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
